[package]
edition.workspace      = true
license.workspace      = true
name                   = "protocol"
rust-version.workspace = true
version.workspace      = true

[dependencies]
defmt = { version = "1.0.1", optional = true }

[features]
defmt = ["dep:defmt"]

[dev-dependencies]
byte       = "0.2.7"
ieee802154 = "0.6.1"
