[package]
edition.workspace      = true
license.workspace      = true
name                   = "remote"
rust-version.workspace = true
version.workspace      = true

[[bin]]
name = "remote"
path = "src/bin/main.rs"
test = false

[lib]
test = false

[dependencies]
cortex-m = { version = "0.7.7", features = [
  "critical-section-single-core",
  "inline-asm",
] }
cortex-m-rt = "0.7.5"
defmt = { workspace = true }
defmt-rtt = "1.0.0"
embassy-executor = { workspace = true, features = [
  "executor-thread",
  "platform-cortex-m",
] }
embassy-nrf = { version = "0.11.0", features = [
  "defmt",
  "gpiote",
  "nrf52840",
  "time",
  "time-driver-rtc1",
] }
embassy-time = { workspace = true, features = ["defmt-timestamp-uptime"] }
panic-probe = { version = "1.0.0", features = ["print-defmt"] }
