name: Continuous Integration

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-checks:
    name: ${{ matrix.crate }} ${{ matrix.name }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ matrix.crate }}
    strategy:
      fail-fast: false
      matrix:
        crate: [driver, remote]
        name: [build, host tests, format, clippy, clippy host]
        include:
          - name: build
            run: cargo build --release
          - name: host tests
            run: cargo test-host
          - name: format
            run: cargo fmt -- --check
          - name: clippy
            run: cargo clippy -- -D warnings
          - name: clippy host
            run: cargo clippy-host -- -D warnings
          - crate: driver
            name: build mqtt
            run: cargo build --release --no-default-features --features mqtt
          - crate: driver
            name: clippy mqtt
            run: cargo clippy --no-default-features --features mqtt -- -D warnings
          - crate: protocol
            name: tests
            run: cargo test
          - crate: protocol
            name: clippy
            run: cargo clippy --all-targets -- -D warnings
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          targets: riscv32imac-unknown-none-elf, thumbv7em-none-eabihf
          toolchain: stable
          components: rust-src, rustfmt, clippy
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: ${{ matrix.crate }} -> ../target
      - name: Run command
        run: ${{ matrix.run }}
